name: Tech Notes Comments

on:
  push:
    paths:
      - "docs/tech_notes/*.md"  # Akcja uruchamia się przy zmianie plików w folderze

jobs:
  add-tech-notes-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Tech Note as Comment
        run: |
          for file in $(find docs/tech_notes -type f -name "*.md"); do
            echo "Processing $file"
            filename=$(basename "$file")
            # Załóżmy, że format to Task_<numer>.md
            issue_number=$(echo "$filename" | sed -n 's/Task_\([0-9]\+\)\.md/\1/p')
            
            if [ -z "$issue_number" ]; then
              echo "Nie znaleziono numeru issue w nazwie pliku $filename"
              continue
            fi
            
            echo "Znaleziono numer issue: $issue_number"
            content=$(cat "$file")
            
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"### Tech Notes\n$content\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/comments"
          done
